INSERT INTO TB_USER (USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (0, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1);
--INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 1);

INSERT INTO TB_AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO TB_AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO TB_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (0, 'ROLE_USER');
INSERT INTO TB_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (0, 'ROLE_ADMIN');
--INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (2, 'ROLE_USER');